test

diff --git a/terraform-ci-dns/action.yml b/terraform-ci-dns/action.yml
--- a/terraform-ci-dns/action.yml
+++ b/terraform-ci-dns/action.yml
@@ -91,28 +91,39 @@ runs:
         PLAN="terraform plan ${{ inputs.planAdditionalVars }} -no-color -out=plan.tfplan -detailed-exitcode"
         $PLAN
         echo "::set-output name=planExitCode::$?"
-        if [[ $? -ne 0 ]]; then
-          planOutput=$(terraform show -no-color plan.tfplan)
-          echo "::set-output name=planResult::$planOutput"
-        fi
         exit 0
       working-directory: ${{ inputs.workingDir }}
       shell: bash
+
+    - name: "Fail if plan failed"
+      id: failIfPlanFailed
+      run: |
+        set -x
+        if [[ ${{ steps.plan.outputs.planExitCode }} -eq 1 ]]; then
+          echo "debug plan failed"
+          exit 1
+        fi
+      working-directory: ${{ inputs.workingDir }}
+      shell: bash
     
-    # - name: "Terraform Show"
-    #   id: show
-    #   run: |
-    #     if [[ ${{ steps.plan.outputs.planExitCode }} -ne 0 ]]; then
-    #       planOutput=$(terraform show -no-color plan.tfplan)
-    #       echo "::set-output name=planResult::$planOutput"
-    #     fi
-    #   working-directory: ${{ inputs.workingDir }}
-    #   shell: bash
+    - name: "Setup Terraform"
+      uses: hashicorp/setup-terraform@v1
+      with:
+          terraform_version: ${{ inputs.terraformVersion }}
+
+    - name: "Terraform Show"
+      id: show
+      run: |
+        if [[ ${{ steps.plan.outputs.planExitCode }} -ne 0 ]]; then
+          terraform show -no-color plan.tfplan
+        fi
+      working-directory: ${{ inputs.workingDir }}
+      shell: bash
 
     - uses: actions/github-script@0.9.0
       name: "Comment plan"
       env:
-        PLAN: "${{ steps.plan.outputs.planResult }}"
+        PLAN: "${{ steps.show.outputs.stdout }}"
         CONDITION: "${{ steps.plan.outputs.planExitCode }}"
       with:
         github-token: ${{ inputs.githubToken }}
@@ -130,7 +141,6 @@ runs:
             \`\`\`
             
             </details>
-            
             *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.workingDir }}\`, Workflow: \`${{ github.workflow }}\`*`;
             github.issues.createComment({
               issue_number: context.issue.number,
